version: '3'

services:
  warehouse:
    image: postgres:13
    container_name: stock
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  pipelinerunner:
    image: stock_price_preciction
    container_name: stock_price_preciction
    build:
      context: ./
      dockerfile: ./stock_price_preciction/Dockerfile
    volumes:
      - ./:/code
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      WAREHOUSE_DB: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WAREHOUSE_PORT: ${POSTGRES_PORT}
